"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:
    Input: s = "abcd" t = "abcde"
    Output: e
    Explanation:
        'e' is the letter that was added.
"""
def findTheDifference(s, t):
    # convert the strings to lists
    s = list(s)
    t = list(t)
    # remove the chars which are in both lists
    for char in s:
        t.remove(char)
    # return the remain char
    return t[0]


s1 = "abcd"
t1 = "abcde"

print(findTheDifference(s1, t1))
